services:

  backend:
    build: ./Backend
    container_name: ecommerce_backend

    ports:
      - "4000:4000"

    env_file:
      - ./Backend/.env

    restart: unless-stopped

  frontend:
    build: ./Frontend
    container_name: ecommerce_frontend

    ports:
      - "5173:5173"

    environment:
      VITE_BACKEND_URL: http://localhost:4000

    depends_on:
      - backend

    restart: unless-stopped

  admin:
    build: ./Admin
    container_name: ecommerce_admin

    ports:
      - "5174:5174"

    environment:
      VITE_BACKEND_URL: http://localhost:4000

    depends_on:
      - backend

    restart: unless-stopped